project_id = "ebuy-platform"

[auth.external.google]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false

[functions.app-rpc]
verify_jwt = false

[functions.public-catalog]
verify_jwt = false

[functions.notifications]
verify_jwt = true

[functions.payment-verification]
verify_jwt = true

[functions.queue-drainer]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.auth-gateway]
verify_jwt = false
