// AUTO-GENERATED — DO NOT HAND-EDIT.
//
// Generated by scripts/generate-rpc-routes.mjs from the single source of
// truth for the action -> domain mapping,
// supabase/functions/_shared/rpc/actions.ts. Run
// `npm run generate:rpc-routes` after changing the action lists there.
//
// packages/domain/src/rpcRoutes.test.ts re-parses actions.ts independently
// and fails npm run test:node if this file has drifted from it, so a hand
// edit (or a forgotten regeneration) is caught by the test suite rather than
// discovered at a misrouted runtime call.

export type RpcFunction =
  | 'feasty-orders'
  | 'feasty-dispatch'
  | 'feasty-partner'
  | 'feasty-admin'
  | 'feasty-account';

/** The compatibility shim every action already routes through today. */
export const LEGACY_RPC_FUNCTION = 'app-rpc' as const;

/** 'split' (default) sends each action to its own domain function; 'legacy' is the kill switch back to the app-rpc shim. */
export type RpcMode = 'split' | 'legacy';

/**
 * Every possible resolved RPC call target: one of the five split-mode domain
 * functions, or the legacy app-rpc shim. Kept as a closed union (not
 * `string`) so a caller can't launder an arbitrary string through
 * resolveRpcTarget and have it typecheck.
 */
export type RpcTarget = RpcFunction | typeof LEGACY_RPC_FUNCTION;

/** The authoritative action -> split-mode Edge Function map. Covers exactly the 59 actions in actions.ts. */
export const RPC_ROUTES: Record<string, RpcFunction> = {
  "customerGetOrders": 'feasty-orders',
  "customerGetOrderDetail": 'feasty-orders',
  "customerListFavoriteRestaurants": 'feasty-orders',
  "customerToggleFavoriteRestaurant": 'feasty-orders',
  "placeCustomerOrder": 'feasty-orders',
  "initializeCustomerPayment": 'feasty-orders',
  "refreshCustomerPaymentStatus": 'feasty-orders',
  "cancelCustomerOrder": 'feasty-orders',
  "customerSendSupportMessage": 'feasty-orders',
  "customerGetSupportThread": 'feasty-orders',
  "dispatchGetDeliveryQueue": 'feasty-dispatch',
  "dispatchGetRiders": 'feasty-dispatch',
  "dispatchGetWeeklyEarnings": 'feasty-dispatch',
  "dispatchGetOrderDetail": 'feasty-dispatch',
  "upsertDispatchRiderProfile": 'feasty-dispatch',
  "syncDispatchRiderLocation": 'feasty-dispatch',
  "dispatchAssignOrderCourier": 'feasty-dispatch',
  "dispatchUpdateOrderStatus": 'feasty-dispatch',
  "submitDispatchApplication": 'feasty-dispatch',
  "partnerGetRestaurantContext": 'feasty-partner',
  "partnerGetRestaurantOrders": 'feasty-partner',
  "partnerGetRestaurantOrder": 'feasty-partner',
  "upsertPartnerRestaurantProfile": 'feasty-partner',
  "claimPartnerRestaurantLink": 'feasty-partner',
  "upsertPartnerRestaurantMenu": 'feasty-partner',
  "partnerUpdateOrderStatus": 'feasty-partner',
  "submitPartnerApplication": 'feasty-partner',
  "adminGetApprovalQueue": 'feasty-admin',
  "adminReviewDispatchApplication": 'feasty-admin',
  "adminReviewPartnerApplication": 'feasty-admin',
  "adminGetDashboardSnapshot": 'feasty-admin',
  "adminGetAccessOverview": 'feasty-admin',
  "supportGetInbox": 'feasty-admin',
  "supportGetConversation": 'feasty-admin',
  "supportSendAgentReply": 'feasty-admin',
  "supportSetConversationStatus": 'feasty-admin',
  "supportAssignConversation": 'feasty-admin',
  "broadcastList": 'feasty-admin',
  "broadcastGet": 'feasty-admin',
  "broadcastPreviewAudience": 'feasty-admin',
  "broadcastCreate": 'feasty-admin',
  "broadcastSchedule": 'feasty-admin',
  "broadcastCancel": 'feasty-admin',
  "promoList": 'feasty-admin',
  "promoCreate": 'feasty-admin',
  "promoSetActive": 'feasty-admin',
  "bootstrapFirstAdmin": 'feasty-admin',
  "promoTrack": 'feasty-account',
  "getPolicyAcceptance": 'feasty-account',
  "recordPolicyAcceptance": 'feasty-account',
  "provisionStaffAccount": 'feasty-account',
  "assignUserRole": 'feasty-account',
  "updateUserRestaurantLink": 'feasty-account',
  "revokeUserRole": 'feasty-account',
  "disableUserAccess": 'feasty-account',
  "enableUserAccess": 'feasty-account',
  "syncUserClaims": 'feasty-account',
  "deleteOwnAccount": 'feasty-account',
  "deleteAdminAccess": 'feasty-account',
};

/** Actions that must be resolvable (and, server-side, callable) before authentication. Mirrors actions.ts's ANONYMOUS_ACTIONS. */
export const ANONYMOUS_RPC_ACTIONS: readonly string[] = ["promoTrack", "bootstrapFirstAdmin"];

/**
 * Resolves the split-mode Edge Function for an action. Throws on an unknown
 * action — a typo'd action name must fail loudly at the call site, never
 * silently hit the wrong function.
 */
export const resolveRpcFunction = (action: string): RpcFunction => {
  const fn = RPC_ROUTES[action];
  if (!fn) {
    throw new Error(`Unknown RPC action: "${action}"`);
  }
  return fn;
};

/**
 * Resolves the function to actually call for an action given the current RPC
 * mode. In 'legacy' mode every known action routes to the app-rpc
 * compatibility shim (the kill switch for a bad split-function deploy);
 * otherwise it routes to the action's split-mode domain function. An unknown
 * action always throws, in either mode — the kill switch recovers a bad
 * deploy, it does not mask a routing typo.
 */
export const resolveRpcTarget = (action: string, mode: RpcMode): RpcTarget => {
  const splitFunction = resolveRpcFunction(action);
  return mode === 'legacy' ? LEGACY_RPC_FUNCTION : splitFunction;
};

/**
 * Normalizes an EXPO_PUBLIC_RPC_MODE / VITE_RPC_MODE env value. Unset,
 * blank, or unrecognized values resolve to 'split' (the safe default)
 * rather than throwing, so a missing or mistyped env var never breaks
 * routing — only the literal value 'legacy' (case-insensitive, trimmed)
 * activates the kill switch.
 */
export const resolveRpcMode = (value: string | undefined | null): RpcMode =>
  value?.trim().toLowerCase() === 'legacy' ? 'legacy' : 'split';
