// AUTO-GENERATED — DO NOT HAND-EDIT.
//
// Generated by scripts/generate-rpc-routes.mjs from the single source of
// truth for the action -> domain mapping,
// supabase/functions/_shared/rpc/actions.ts. Run
// `npm run generate:rpc-routes` after changing the action lists there.
//
// packages/domain/src/rpcRoutes.test.ts re-parses actions.ts independently
// and fails npm run test:node if this file has drifted from it, so a hand
// edit (or a forgotten regeneration) is caught by the test suite rather than
// discovered at a misrouted runtime call.

export type RpcFunction =
  | 'feasty-orders'
  | 'feasty-dispatch'
  | 'feasty-partner'
  | 'feasty-admin'
  | 'feasty-account';

/** The compatibility shim every action already routes through today. */
export const LEGACY_RPC_FUNCTION = 'app-rpc' as const;

/** 'split' (default) sends each action to its own domain function; 'legacy' is the kill switch back to the app-rpc shim. */
export type RpcMode = 'split' | 'legacy';

/**
 * Every possible resolved RPC call target: one of the five split-mode domain
 * functions, or the legacy app-rpc shim. Kept as a closed union (not
 * `string`) so a caller can't launder an arbitrary string through
 * resolveRpcTarget and have it typecheck.
 */
export type RpcTarget = RpcFunction | typeof LEGACY_RPC_FUNCTION;

/**
 * Runtime-checkable list of every valid RpcTarget value. RpcTarget only
 * exists at compile time; packages/domain/src/rpcUrl.ts's
 * deriveRpcFunctionUrl needs this at runtime to validate that the URL
 * segment it's about to replace is actually a known Edge Function name
 * rather than guessing — e.g. refusing to mistake an API-version segment
 * like "v1" for a function name.
 */
export const KNOWN_RPC_TARGETS: readonly RpcTarget[] = ['feasty-orders', 'feasty-dispatch', 'feasty-partner', 'feasty-admin', 'feasty-account', LEGACY_RPC_FUNCTION];

/** The authoritative action -> split-mode Edge Function map. Covers exactly the 91 actions in actions.ts. */
export const RPC_ROUTES: Record<string, RpcFunction> = {
  "customerGetOrders": 'feasty-orders',
  "customerGetOrderDetail": 'feasty-orders',
  "customerListFavoriteRestaurants": 'feasty-orders',
  "customerToggleFavoriteRestaurant": 'feasty-orders',
  "placeCustomerOrder": 'feasty-orders',
  "initializeCustomerPayment": 'feasty-orders',
  "refreshCustomerPaymentStatus": 'feasty-orders',
  "cancelCustomerOrder": 'feasty-orders',
  "customerSendSupportMessage": 'feasty-orders',
  "customerGetSupportThread": 'feasty-orders',
  "customerSubmitOrderRating": 'feasty-orders',
  "customerGetPendingRatings": 'feasty-orders',
  "customerValidatePromoCode": 'feasty-orders',
  "dispatchGetDeliveryQueue": 'feasty-dispatch',
  "dispatchGetRiders": 'feasty-dispatch',
  "dispatchGetWeeklyEarnings": 'feasty-dispatch',
  "dispatchGetShiftSlots": 'feasty-dispatch',
  "dispatchGetOrderDetail": 'feasty-dispatch',
  "upsertDispatchRiderProfile": 'feasty-dispatch',
  "dispatchUpsertShiftSlots": 'feasty-dispatch',
  "syncDispatchRiderLocation": 'feasty-dispatch',
  "dispatchGetNearestRiders": 'feasty-dispatch',
  "dispatchAssignOrderCourier": 'feasty-dispatch',
  "dispatchUpdateOrderStatus": 'feasty-dispatch',
  "submitDispatchApplication": 'feasty-dispatch',
  "dispatchAcceptOffer": 'feasty-dispatch',
  "dispatchDeclineOffer": 'feasty-dispatch',
  "partnerGetRestaurantContext": 'feasty-partner',
  "partnerGetRestaurantOrders": 'feasty-partner',
  "partnerGetRestaurantRatings": 'feasty-partner',
  "partnerInviteStaff": 'feasty-partner',
  "partnerListStaff": 'feasty-partner',
  "partnerRevokeStaffAccess": 'feasty-partner',
  "partnerRevokeStaffInvite": 'feasty-partner',
  "partnerGetRestaurantOrder": 'feasty-partner',
  "upsertPartnerRestaurantProfile": 'feasty-partner',
  "claimPartnerRestaurantLink": 'feasty-partner',
  "upsertPartnerRestaurantMenu": 'feasty-partner',
  "partnerUpdateOrderStatus": 'feasty-partner',
  "submitPartnerApplication": 'feasty-partner',
  "partnerSetMenuItemAvailability": 'feasty-partner',
  "partnerSetStorePause": 'feasty-partner',
  "resolvePartnerBankAccount": 'feasty-partner',
  "requestPartnerVerificationUploadUrl": 'feasty-partner',
  "submitPartnerOnboarding": 'feasty-partner',
  "adminGetApprovalQueue": 'feasty-admin',
  "adminReviewDispatchApplication": 'feasty-admin',
  "adminReviewPartnerApplication": 'feasty-admin',
  "adminSetRestaurantPublished": 'feasty-admin',
  "adminGetDashboardSnapshot": 'feasty-admin',
  "adminGetAccessOverview": 'feasty-admin',
  "adminGetAuditLog": 'feasty-admin',
  "adminGetRiskEvents": 'feasty-admin',
  "adminListFeatureFlags": 'feasty-admin',
  "adminUpsertFeatureFlag": 'feasty-admin',
  "adminGetOperationalAlerts": 'feasty-admin',
  "supportGetInbox": 'feasty-admin',
  "supportGetConversation": 'feasty-admin',
  "supportSendAgentReply": 'feasty-admin',
  "supportSetConversationStatus": 'feasty-admin',
  "supportAssignConversation": 'feasty-admin',
  "broadcastList": 'feasty-admin',
  "broadcastGet": 'feasty-admin',
  "broadcastPreviewAudience": 'feasty-admin',
  "broadcastCreate": 'feasty-admin',
  "broadcastSchedule": 'feasty-admin',
  "broadcastCancel": 'feasty-admin',
  "promoList": 'feasty-admin',
  "promoCreate": 'feasty-admin',
  "promoSetActive": 'feasty-admin',
  "adminListPromoCodes": 'feasty-admin',
  "adminCreatePromoCode": 'feasty-admin',
  "adminSetPromoCodeActive": 'feasty-admin',
  "bootstrapFirstAdmin": 'feasty-admin',
  "promoTrack": 'feasty-account',
  "getFeatureFlags": 'feasty-account',
  "getPolicyAcceptance": 'feasty-account',
  "recordPolicyAcceptance": 'feasty-account',
  "provisionStaffAccount": 'feasty-account',
  "redeemStaffInvite": 'feasty-account',
  "staffInviteCreateAccount": 'feasty-account',
  "staffInviteResolve": 'feasty-account',
  "assignUserRole": 'feasty-account',
  "updateUserRestaurantLink": 'feasty-account',
  "revokeUserRole": 'feasty-account',
  "disableUserAccess": 'feasty-account',
  "enableUserAccess": 'feasty-account',
  "syncUserClaims": 'feasty-account',
  "deleteOwnAccount": 'feasty-account',
  "deleteAdminAccess": 'feasty-account',
  "deleteUserAccountOnRequest": 'feasty-account',
};

/**
 * Resolves the split-mode Edge Function for an action. Throws on an unknown
 * action — a typo'd action name must fail loudly at the call site, never
 * silently hit the wrong function.
 */
export const resolveRpcFunction = (action: string): RpcFunction => {
  const fn = RPC_ROUTES[action];
  if (!fn) {
    throw new Error(`Unknown RPC action: "${action}"`);
  }
  return fn;
};

/**
 * Resolves the function to actually call for an action given the current RPC
 * mode. In 'legacy' mode every known action routes to the app-rpc
 * compatibility shim (the kill switch for a bad split-function deploy);
 * otherwise it routes to the action's split-mode domain function. An unknown
 * action always throws, in either mode — the kill switch recovers a bad
 * deploy, it does not mask a routing typo.
 */
export const resolveRpcTarget = (action: string, mode: RpcMode): RpcTarget => {
  const splitFunction = resolveRpcFunction(action);
  return mode === 'legacy' ? LEGACY_RPC_FUNCTION : splitFunction;
};

/**
 * Normalizes an EXPO_PUBLIC_RPC_MODE / VITE_RPC_MODE env value. Unset,
 * blank, or unrecognized values resolve to 'split' (the safe default)
 * rather than throwing, so a missing or mistyped env var never breaks
 * routing — only the literal value 'legacy' (case-insensitive, trimmed)
 * activates the kill switch.
 *
 * Honest recovery path — this is NOT a runtime flip: EXPO_PUBLIC_RPC_MODE /
 * VITE_RPC_MODE are inlined into the bundle at build time (Metro for the
 * three Expo web apps, Vite for admin-web), so recovering from a bad
 * split-function deploy means editing the value in
 * .github/workflows/deploy-{customer,partner,admin}.yml (and .env.apps for
 * local builds) and letting CI rebuild + redeploy — a workflow edit plus a
 * redeploy, not an instant flip. Installed native mobile builds (customer/
 * partner/dispatch on iOS/Android) need an EAS Update or a store release to
 * pick up the change; there is no web-only equivalent for those.
 */
export const resolveRpcMode = (value: string | undefined | null): RpcMode =>
  value?.trim().toLowerCase() === 'legacy' ? 'legacy' : 'split';
