// Smoke tests for the five domain-scoped RPC entrypoints added in task A2
// (feasty-orders, feasty-dispatch, feasty-partner, feasty-admin,
// feasty-account). Each function's index.ts does exactly two things: import
// its own domain module and call `buildDispatcher([<thatDomain>])`. This
// suite reproduces that exact construction against the REAL domain modules
// (not synthetic stubs) so that importing the wrong domain into one of the
// five index.ts files — the mis-wiring this suite exists to catch — would
// show up here as a wrong action list, not just at review time.
//
// Three assertions per function:
//
//   1. An action that belongs to a *different* domain (proxy for "an action
//      this function does not implement") resolves to no handler under
//      either lookup. That null is exactly what _shared/rpc/serve.ts's
//      `executeAction` turns into the 501 "not implemented in the native
//      Supabase backend" response — the SAME literal code path app-rpc has
//      used all along (see serve.ts, `nativeResponse ?? json(501, ...)`).
//      task-2-brief.md calls this a 404; it is not, and Task 1 deliberately
//      kept 501 for an unimplemented action. This suite follows the code.
//
//   2. A privileged (non-anonymous) action belonging to that function's own
//      domain, requested with no Authorization header, is rejected 401
//      before any handler executes — proof the auth-first ordering survived
//      moving the dispatcher into its own Edge Function. No mocking needed:
//      `_shared/auth.ts`'s `getBearerToken` throws before any network call.
//
//   3. That SAME privileged action, requested by an authenticated caller,
//      does NOT answer 501 — it reaches a real handler in THIS dispatcher.
//      This is the assertion that actually catches a wrong-domain import:
//      assertions 1 and 2 alone do not (see note below). "Not 501" on its
//      own would also be satisfied by an unrelated 500 if the handler ran
//      far enough to hit the patched client and blew up on its shape, which
//      would prove nothing about wiring. To make the assertion sound, the
//      fake authenticated profile below carries a role
//      (`'smoke-test-role'`) that is not a real app role and therefore fails
//      every one of these five actions' `ensureRole(...)` check — which is
//      each handler's first line, before any DB call. So a correctly wired
//      dispatcher deterministically answers exactly 403
//      "You do not have permission to perform this action.": proof a real
//      handler ran (the message is generated by `ensureRole`, which lives
//      inside the handler, not in the dispatcher or the HTTP wrapper), and
//      proof it never touched the mocked `serviceClient.from(...)` shape (so
//      this assertion is not sensitive to what that mock does or doesn't
//      support). A wrong-domain swap makes the action resolve to no handler
//      in this dispatcher, which answers 501 instead — the assertion fails,
//      exactly as intended.
//
// Why assertions 1 and 2 alone are not enough (the finding this revision
// fixes): each fixture's `foreignAction` is owned by exactly one *other*
// domain, so assertion 1 only fails if the dispatcher was wired to that one
// specific wrong domain — the other three of four possible wrong-domain
// substitutions leave `foreignAction` unregistered either way and assertion
// 1 stays green. Assertion 2 has no discriminating power at all: auth runs
// before handler lookup for every non-anonymous action regardless of which
// domain (if any) is registered, so an unauthenticated request for the
// function's own privileged action answers 401 no matter what the dispatcher
// was built from. Assertion 3 is the one that depends on the actual handler
// map of the actual dispatcher under test, so it is the one that fails for
// all four wrong-domain substitutions, not just one.
//
// Getting an authenticated HTTP response out of createRpcHttpHandler (used
// by assertions 1 and 3) without a live Supabase project requires monkey-
// patching the shared `serviceClient` singleton's `auth.getUser` / `from(...)`
// so `getAuthenticatedRequestContext` resolves with a fake profile.
// Assertion 2 never reaches this — it throws before any network call, real
// or faked, is made.
//
// Runs env-vars-then-dynamic-import, same as registry.real-domains.test.ts
// and for the same reason: the domain modules import _shared/client.ts,
// which throws at module-evaluation time without SUPABASE_URL /
// SERVICE_ROLE_KEY, and a hoisted top-level `import` would run before this
// file's test bodies get a chance to set them. See that file for the fuller
// explanation, including why this lives in package.json's second, --no-check
// `deno test` invocation rather than the type-checked one.

Deno.env.set('SUPABASE_URL', 'http://localhost:54321');
Deno.env.set('SERVICE_ROLE_KEY', 'test-service-role-key-not-real');

const [
  { ordersDomain },
  { dispatchDomain },
  { partnerDomain },
  { adminDomain },
  { accountDomain },
] = await Promise.all([
  import('../domains/orders.ts'),
  import('../domains/dispatch.ts'),
  import('../domains/partner.ts'),
  import('../domains/admin.ts'),
  import('../domains/account.ts'),
]);

const { buildDispatcher } = await import('./registry.ts');
const { createRpcHttpHandler } = await import('./serve.ts');
const { serviceClient } = await import('../client.ts');

// Monkey-patch the shared service-role client so getAuthenticatedRequestContext
// resolves without a live Supabase project. Assertion 2 (the 401 case) never
// reaches this — it throws before any network call, real or faked.
//
// The fake profile's role is deliberately NOT a real app role. Every one of
// the five `privilegedAction`s below starts its handler with
// `ensureRole(context.role, [...])` against some subset of
// {'customer','admin','dispatch','restaurant'} — never this sentinel — so an
// authenticated request that reaches a real handler always fails that check
// first, before the handler ever calls `serviceClient.from(...)`. That is
// what makes assertion 3 sound: the mocked `from(...)` below only needs to
// support the one `user_profiles` lookup inside
// `getAuthenticatedRequestContext` itself; no domain handler's own queries
// ever run.
const FAKE_UID = 'smoke-test-uid';
const FAKE_ROLE = 'smoke-test-role';
const fakeUser = { id: FAKE_UID, email: 'smoketest@example.test', app_metadata: {} };

// deno-lint-ignore no-explicit-any
(serviceClient.auth as any).getUser = async () => ({ data: { user: fakeUser }, error: null });
// deno-lint-ignore no-explicit-any
(serviceClient as any).from = (_table: string) => ({
  select: (_columns: string) => ({
    eq: (_column: string, _value: string) => ({
      maybeSingle: async () => ({
        data: {
          uid: FAKE_UID,
          email: fakeUser.email,
          role: FAKE_ROLE,
          accountDisabled: false,
        },
        error: null,
      }),
    }),
  }),
});

const PERMISSION_DENIED_MESSAGE = 'You do not have permission to perform this action.';

const expectEqual = (actual: unknown, expected: unknown, label: string) => {
  if (actual !== expected) {
    throw new Error(`${label}: expected ${expected}, got ${actual}`);
  }
};

const postRequest = (action: string, headers: HeadersInit = {}) =>
  new Request('https://example.test/rpc', {
    body: JSON.stringify({ action, data: {} }),
    headers: { 'content-type': 'application/json', ...headers },
    method: 'POST',
  });

const AUTHED_HEADERS = { authorization: 'Bearer fake-jwt-for-smoke-test' };

type EntrypointFixture = {
  // deno-lint-ignore no-explicit-any
  domain: any;
  foreignAction: string;
  functionName: string;
  privilegedAction: string;
};

// Each fixture's `foreignAction` is a real action owned by a *different*
// domain — proof this function's dispatcher, built the same way its index.ts
// builds it, does not accidentally answer for another domain's action.
// Each fixture's `privilegedAction` is a real action owned by ITS OWN
// domain — the one assertion 3 uses to prove the dispatcher actually
// resolves it, under any of the four possible wrong-domain substitutions.
const FIXTURES: EntrypointFixture[] = [
  {
    domain: ordersDomain,
    foreignAction: 'dispatchGetRiders',
    functionName: 'feasty-orders',
    privilegedAction: 'customerGetOrders',
  },
  {
    domain: dispatchDomain,
    foreignAction: 'partnerGetRestaurantContext',
    functionName: 'feasty-dispatch',
    privilegedAction: 'dispatchGetRiders',
  },
  {
    domain: partnerDomain,
    foreignAction: 'adminGetDashboardSnapshot',
    functionName: 'feasty-partner',
    privilegedAction: 'partnerGetRestaurantContext',
  },
  {
    domain: adminDomain,
    foreignAction: 'customerGetOrders',
    functionName: 'feasty-admin',
    privilegedAction: 'adminGetDashboardSnapshot',
  },
  {
    domain: accountDomain,
    foreignAction: 'upsertDispatchRiderProfile',
    functionName: 'feasty-account',
    privilegedAction: 'assignUserRole',
  },
];

for (const fixture of FIXTURES) {
  const dispatcher = buildDispatcher([fixture.domain]);
  const handler = createRpcHttpHandler(fixture.functionName, dispatcher);

  Deno.test(
    `${fixture.functionName}: an action outside its own domain answers 501, not 404, for an authenticated caller`,
    async () => {
      const response = await handler(postRequest(fixture.foreignAction, AUTHED_HEADERS));
      expectEqual(response.status, 501, `${fixture.functionName} foreign-action status`);
      const body = await response.json();
      expectEqual(
        body?.error?.message,
        `The RPC action "${fixture.foreignAction}" is not implemented in the native Supabase backend.`,
        `${fixture.functionName} foreign-action error message`
      );
    }
  );

  Deno.test(
    `${fixture.functionName}: an unauthenticated privileged action is rejected 401, never executed`,
    async () => {
      const response = await handler(postRequest(fixture.privilegedAction));
      expectEqual(response.status, 401, `${fixture.functionName} unauthenticated privileged-action status`);
    }
  );

  Deno.test(
    `${fixture.functionName}: its own privileged action resolves to a real handler in this dispatcher, not 501`,
    async () => {
      const response = await handler(postRequest(fixture.privilegedAction, AUTHED_HEADERS));
      expectEqual(response.status, 403, `${fixture.functionName} own-action authenticated status`);
      const body = await response.json();
      expectEqual(
        body?.error?.message,
        PERMISSION_DENIED_MESSAGE,
        `${fixture.functionName} own-action authenticated error message`
      );
    }
  );
}
